### ISSUE TITLE
Provide functions to read/write string directly to Arena

### ISSUE THREAD

**Issue by mangalaman93** [grandecola/bigqueue#19]
Currently, we need to first copy the string (say) into an array of bytes. Then, we will copy this array into the Arena. The double copy can be avoided.

**Comment by darkcoderrises** [comment]
Hi, I would like to work on this.

**Comment by mangalaman93** [comment]
We have got two choices here -
1. Either we allow type of the queue. A queue could be of type int, string, []byte. This would mean that a queue can store only one type of elements. We store the type of the queue in index and allow only corresponding write functions, disable the rest.
2. In this choice, a queue can have any type of values. The type of the element is decides by the header that we will put into the data file. This may increase storage requirement a bit.

**Comment by darkcoderrises** [comment]
I think the first one would be better. If the use case requires information about each member of the queue, then that could be handled later on.

**Comment by mangalaman93** [comment]
One more idea, in this case we stop worry about the type, and only provide helper functions so that -
 * users don't have to worry about serialization and deserialization
 * more efficiency, avoids one copy

One will still have to know what typed function to call (i.e. call `ReadString` or `ReadUint64`).

For example, for writing, we will have to define following internal interface -
```go
type mmapData interface {
	Len() int
	Write(m mmap.IMmap, offset, from, to int) error
}
```

Let's say we want to write String into the mapped area, we will define following types -
```go
type mmapString struct {
  s string
}

func (s *mmapString) Len() int {
  return len(s.s)
}

func (s *mmapString) Write(m mmap.IMmap, offset, from, to int) error {
  _, err := m.WriteString(s[from:to], offset) // this function needs to be added to mmap lib
  return err
}
```

Now, we can implement a generic function that takes an object of type `mmapData` and write it to mapped area by writing it's length first and then the value, possibly into multiple arenas if necessary.

**Comment by darkcoderrises** [comment]
Yeah that seems better
