### ISSUE TITLE
Ensure that it is okay to not have Arena Size in multiple of page size

### ISSUE THREAD

**Issue by mangalaman93** [grandecola/bigqueue#21]

**Comment by zeoaman** [comment]
It doesn't make sense to restrict Arena size to power of 2 or page size actually. It only leads to memory wastage when we perform `mmap` given that mmap will always consume memory in multiple of `os page size`

**Comment by mangalaman93** [comment]
It doesn't make sense to restrict Arena size to power of 2 or page size actually. It only leads to memory wastage when we perform mmap given that mmap will always consume memory in multiple of os page size which is fine if user chooses to do so. It will cause us problems if ever os page size changes in future.
