### ISSUE TITLE
Update APIs to use offsets

### ISSUE THREAD

**Issue by mangalaman93** [grandecola/bigqueue#51]
This is along the lines of how Kafka works. Given that bigqueue is persistent, it makes a lot of sense to not delete the data after it is read once. Certainly, it could be configured to do so, but that shouldn't be the default choice. Instead, we should allow using offsets per client so that the data could be read from anywhere in the queue as needed.

**Comment by mangalaman93** [comment]
I was thinking something along the lines -
```
q := NewQueue()
(q *Queue) NewConsumer() (*Consumer, error)
(q *Queue) NewProducer() (*Producer, error)
(q *Queue) Close() error

(c *Consumer) Peek(policy Policy) ([]byte, error)
(c *Consumer) PeekString(policy Policy) (string, error)
(c *Consumer) Next() error

(p *Producer) Enqueue(b []byte) error
(p *Producer) EnqeueuString(s string) error

type Policy struct {
  block    bool
  timeout time.Duration
}
```

**Comment by mangalaman93** [comment]
This is the final API -
  * We can have only one producer, which can be shared across multiple routines.
  * Multiple consumers are allowed and can read from different offsets simultaneously.

```
NewQueue(dir string, opts ...Option)
IsEmpty() bool
Flush() error
Close() error

(q *Queue) Enqueue(b []byte) error
(q *Queue) EnqueueString(s string) error

(q *Queue) NewConsumer(opts ...ConsumerOption) (*Consumer, error)
(c *Consumer) Dequeue() error
(c *Consumer) DequeueString() error
```

**Comment by mangalaman93** [comment]
## Data Formats

### Metadata File

| Bytes | Data |
|-------|----------------------|
| 0-7 | version Number |
| 8-15 | tail arena id |
| 16-23 | tail byte offset in arena |
| 24-31 | arena size |
| 32-39| length of the queue |
| repeated | |
| 40-47 | length of consumer name (L) |
| 48-55 | arena id (head) of consumer |
| 56-63 | byte offset in the arena (head) of consumer |
| 64-(L+63) | consumer name |

### Index File

| Bytes | Data |
|-------|----------------------|
| repeated | |
| 0-7 | arena id |
| 8-15 | position of first element in the queue |
| 16-23 | first element byte offset in the arena |

### Arena File

| Bytes | Data |
|-------|----------------------|
| n - (n+7) | length of element |
| (n+8) - (n+7+L)  | element of size L |

**Comment by eeliu** [comment]
> I was thinking something along the lines -
> 
> ```
> q := NewQueue()
> (q *Queue) NewConsumer() (*Consumer, error)
> (q *Queue) NewProducer() (*Producer, error)
> (q *Queue) Close() error
> 
> (c *Consumer) Peek() ([]byte, error)
> (c *Consumer) PeekString() (string, error)
> (c *Consumer) Dequeue() error
> (c *Consumer) PeekAndDequeue() error
> 
> (p *Producer) Enqueue(b []byte) error
> (p *Producer) EnqeueuString(s string) error
> 
> type Policy struct {
>   block    bool
>   timeout time.Duration
> }
> ```



@mangalaman93 Thanks the wonderful bigqueue!

Does these API (Peek/PeekString) removed , do I have alternative APIs?
