### ISSUE TITLE
Add PeekAndDequeue function and update external sort example

### ISSUE THREAD

**Issue by mangalaman93** [grandecola/bigqueue#58]
@darkcoderrises

**Comment by mangalaman93** [comment]
can't remember why we needed this @darkcoderrises?

**Comment by darkcoderrises** [comment]
I think it was on the lines of test and set

**Comment by mangalaman93** [comment]
But in external sort, we are not dequeue-ing in parallel, right?

**Comment by mangalaman93** [comment]
Closing this in lieu of new API #51
